title: 九大突破塾
description: 九大・国公立大合格へ最短ルートで導く 大学受験・トップ高校受験 専門塾（福岡市城南区）
url: https://www.homeforstudyandvictory.com
timezone: Asia/Tokyo
markdown: kramdown
permalink: /news/:year/:month/:day/:title/
exclude: [README.md]
